function [fitresult, gof] = createFit3(x3_2, y3_2)
%CREATEFIT(X3_2,Y3_2)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x3_2
%      Y Output: y3_2
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 15-Apr-2021 23:04:33


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x3_2, y3_2 );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y3_2 vs. x3_2', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x3_2', 'Interpreter', 'none' );
ylabel( 'y3_2', 'Interpreter', 'none' );
grid on


